### ISSUE TITLE
CSRF token missing

### ISSUE THREAD

**Issue by guangbochen** [miguelgrinberg/flasky#1]
I run the application with $ python manage.py runserver,
I can't login becuase of CSRF token missing,
can someone tell me how to fix it properly, thanks in advance.

and when I run the test code
there is one test fail - test_comments (test_api.APITestCase) ... FAIL

FAIL: test_comments (test_api.APITestCase)
Traceback (most recent call last):
  File "/Users/guangbo/Sites/flasky/tests/test_api.py", line 217, in test_comments
    'Good < a rel="nofollow" href="http://example.com" >post< /a >!')
AssertionError: False is not true

**Comment by yulincj6** [comment]
thank GOD!! this post save my day :+1:

**Comment by Neroldy** [comment]
Is this issue fixed in the Flask-Login==0.3.0?
I still have this problem.

alembic==0.8.2
bleach==1.4.2
blinker==1.4
dominate==2.1.12
Flask==0.10.1
Flask-Bootstrap==3.3.5.6
Flask-HTTPAuth==2.7.0
Flask-Login==0.3.0
Flask-Mail==0.9.1
Flask-Migrate==1.5.1
Flask-Moment==0.5.1
Flask-PageDown==0.2.1
Flask-Script==2.0.5
Flask-SQLAlchemy==2.0
Flask-WTF==0.12
ForgeryPy==0.1
html5lib==0.9999999
itsdangerous==0.24
Jinja2==2.8
Mako==1.0.2
Markdown==2.6.2
MarkupSafe==0.23
py2exe==0.9.2.2
python-editor==0.4
six==1.9.0
SQLAlchemy==1.0.8
Werkzeug==0.10.4
WTForms==2.0.2

**Comment by miguelgrinberg** [comment]
@Neroldy Maybe there's been a regression? This issue has been fixed long ago.

The 0.3 release of Flask-Login also introduces breaking changes, this code in this repository has been updated to work with 0.3, so when you downgrade to any 0.2.x release you will see errors in how the `is_authenticated` and `is_anonymous` properties are used. (in 0.3 these are properties, in 0.2.x they were methods).

**Comment by maxcountryman** [comment]
@miguelgrinberg are you able to confirm `'strong'` session protection is working? We had a couple of other users report an error after the release. maxcountryman/flask-login/issues/231

**Comment by DmonteiroD** [comment]
@maxcountryman I have same issue. with strong Flask-Login==0.3.0 
Initially the form has a crsf token, but after the submit the CSRF token is empty. This only occurs with strong.

**Comment by Neroldy** [comment]
@miguelgrinberg @maxcountryman @DmonteiroD 
Thanks for you guys reply!
When I roll back to the flask-login 0.2.7, I also have another problem is that "AttributeError: 'AnonymousUser' object has no attribute 'ping'" when I try to visit http://127.0.0.1:5000/.

**Comment by miguelgrinberg** [comment]
@Neroldy see my previous comment. Flask-Login 0.3 is incompatible with previous releases, the application needs to change.

@maxcountryman I can confirm that I'm also seeing a regression on this, using the app in this repository. Let me investigate a bit more what's going on.

**Comment by Neroldy** [comment]
@miguelgrinberg OK, Thanks~ ^_^

**Comment by lzp819739483** [comment]
@miguelgrinberg @guangbochen 
Thanks !!!
I solved this question with  comments 'strong' like this
` # login_manager.session_protection = 'strong'`

**Comment by leonardocintra** [comment]
I still have this problem!
I using:
# python 3.4
# flask-login: 0.3.0
# flask-wtf: 0.12

What was the solution that you guys applied?
`Obs: I am in [9a tag](https://github.com/miguelgrinberg/flasky/tree/9a)

**Comment by miguelgrinberg** [comment]
@leonardocintra install Flask-Login from git master and the problem will be solved. We are waiting for @maxcountryman to cut a 0.3.1 release with the fix for this bug.

**Comment by leonardocintra** [comment]
Thank you @miguelgrinberg !! It is ok! :+1:

**Comment by januszdotnl** [comment]
I had the same problem. I was able to solve the problem with  # pip uninstall flask-login and then # easy_install flask-login . Thanks for the help!

**Comment by maxcountryman** [comment]
As of yesterday morning, `0.3.1` has been released. Please use this version going forward.

**Comment by zomgs** [comment]
Thank you. It's back to the usual behaviour with this release!

**Comment by Neroldy** [comment]
Thanks~
@miguelgrinberg 
@maxcountryman

**Comment by Moxmi** [comment]
i have removed flask-login,but why this error still raise?

**Comment by Moxmi** [comment]
@miguelgrinberg i change the flask-login(0.3.2) to flask-login(0.3.1) version and set WTF_CSRF_ENABLED=False, but can not resolved the csrf token missing error, could you help me?Thx!

**Comment by Moxmi** [comment]
i resolved this problem, because the flask-wtf(<0.9.0) should use CSRF_ENABLED instead of WTF_CSRF_ENABLED !!!!!!

**Comment by felexkemboi** [comment]
TypeError: 'AnonymousUserMixin' object is not callable

**Comment by felexkemboi** [comment]
@miquelgrinberg@Neroldy.......help me debug please

**Comment by miguelgrinberg** [comment]
@felexkemboi can you show the complete stack trace of the error?

**Comment by webguybit** [comment]
@miguelgrinberg & All
I was developing application on my local env. Here is my pip freeze
```
asn1crypto==0.24.0
Babel==2.6.0
blinker==1.4
certifi==2018.10.15
cffi==1.11.5
chardet==3.0.4
Click==7.0
cryptography==2.4.2
Flask==1.0.2
Flask-Admin==1.5.2
Flask-BabelEx==0.9.3
Flask-Login==0.4.1
Flask-Mail==0.9.1
Flask-Principal==0.4.0
Flask-Security==3.0.0
Flask-WTF==0.14.2
idna==2.7
itsdangerous==1.1.0
Jinja2==2.10
MarkupSafe==1.1.0
passlib==1.7.1
peewee==3.7.1
pycparser==2.19
pyDes==2.0.1
PyMySQL==0.9.2
pyOpenSSL==18.0.0
pytz==2018.7
requests==2.20.1
six==1.11.0
speaklater==1.3
urllib3==1.24.1
Werkzeug==0.14.1
wtf-peewee==3.0.0
WTForms==2.2.1
xlrd==1.1.0
```

So, Flask-Login is 0.4.1. Everything was fine before. But when I clear cookies from chrome for 127.0.0.1, it has started to show Bad Request CSRF Token is missing while trying to submit a login form. In my flask view and template files, all of the suggested config are done though. 
i.e: 
```
from flask_wtf.csrf import CSRFProtect 
app.config['SECRET_KEY'] = 'blablabla'
csrf = CSRFProtect(app)
```
and in template under form tag :
`<input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>`

Any help/hint would be appreciated. 
Thanks

**Comment by miguelgrinberg** [comment]
@webguybit Is this for a form or for something else? See the [documentation](https://flask-wtf.readthedocs.io/en/stable/csrf.html), the `CSRFProtect()` class isn't used with forms, the forms already have their own CSRF handling.

**Comment by dongzhonghua** [comment]
**WTF_CSRF_ENABLED = False**  works for me

**Comment by miguelgrinberg** [comment]
@dongzhonghua you may be making your application insecure if you do that. CSRF is there for a reason, not a good idea to disable it without understanding the consequences.

**Comment by dongzhonghua** [comment]
thanks for your notice, my project is just for practice, so secure problem is not important to me. But I will take this issue seriously in the future.

**Comment by dongzhonghua** [comment]
> @dongzhonghua you may be making your application insecure if you do that. CSRF protection is there for a reason, not a good idea to disable it without understanding the consequences.

thanks for your notice, my project is just for practice, so secure problem is not important to me. But I will take this issue seriously in the future.

**Comment by pyhire-git** [comment]
@miguelgrinberg this problem is still happen to me.

Flask-Login is 0.4.1

> pip freeze 

alembic==1.0.11
amqp==2.5.0
asn1crypto==0.24.0
astroid==2.2.5
atomicwrites==1.3.0
attrs==19.1.0
autopep8==1.4.4
Babel==2.7.0
billiard==3.6.0.0
blinker==1.4
celery==4.3.0
certifi==2019.6.16
cffi==1.11.5
chardet==3.0.4
Click==7.0
cryptography==2.3.1
dnspython==1.16.0
eventlet==0.25.0
Flask==1.0.3
Flask-Alembic==2.0.1
flask-allows==0.7.1
Flask-BabelPlus==2.1.1
Flask-Caching==1.7.2
Flask-Cors==3.0.8
Flask-Limiter==1.0.1
**Flask-Login==0.4.1**
Flask-Mail==0.9.1
flask-mongoengine==0.9.5
flask-redis==0.4.0
Flask-SQLAlchemy==2.4.0
Flask-Themes2==0.1.4
flask-whooshee==0.7.0
Flask-WTF==0.14.2
gevent==1.4.0
greenlet==0.4.15
gunicorn==19.9.0
idna==2.8
importlib-metadata==0.18
inflect==2.1.0
isort==4.3.20
itsdangerous==1.1.0
Jinja2==2.10.1
kombu==4.6.3
lazy-object-proxy==1.4.1
limits==1.3
loginform==1.2.0
lxml==4.3.4
Mako==1.0.12
MarkupSafe==1.1.1
mccabe==0.6.1
mongoengine==0.18.2
monotonic==1.5
more-itertools==7.0.0
packaging==19.0
pipenv==2018.11.26
pluggy==0.12.0
py==1.8.0
pycodestyle==2.5.0
pycparser==2.19
pylint==2.3.1
pymongo==3.8.0
PyMySQL==0.9.3
pyparsing==2.4.0
pytest==4.6.3
python-dateutil==2.8.0
python-editor==1.0.4
pytz==2019.1
raven==6.10.0
redis==3.2.1
requests==2.22.0
sentry-sdk==0.8.0
simplejson==3.16.0
six==1.12.0
sqlacodegen==2.0.1
SQLAlchemy==1.3.5
typed-ast==1.4.0
urllib3==1.25.3
vine==1.3.0
virtualenv==16.6.1
virtualenv-clone==0.5.3
wcwidth==0.1.7
Werkzeug==0.15.4
Whoosh==2.7.4
wrapt==1.11.1
WTForms==2.2.1
zipp==0.5.1

**Comment by miguelgrinberg** [comment]
@pyhire-git are you using session protection set to strong in Flask-Login? See https://github.com/miguelgrinberg/flasky/issues/178, strong has been broken for a long time, the current version of this project uses basic session protection, which is the default.

**Comment by ancalita** [comment]
@miguelgrinberg Hi, I've just deployed my own Flask app using WTForms & Flask-Login (without session protection set to strong) on Heroku. If I try to register test users  or login existing test users, I receive 400 Bad Request CSRF session token is missing error.

I have done everything by the book:
1) I have set both SECRET_KEY & WTF_CSRF_SECRET_KEY as config vars in Heroku
2) in the __init__ file, I call csrf = CSRFProtect() globally , then in the application factory create_app() I do csrf.init_app(app)
3) my form classes inherit from FlaskForm
4) in html files, in the form tag, I call {{ form.csrf_token }}

Could you please provide guidance for further troubleshooting?

Please see below the contents of my requirements.txt:
alembic==1.4.3
blinker==1.4
Bootstrap-Flask==1.5
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
dnspython==2.0.0
email-validator==1.1.1
Flask==1.1.2
**Flask-Login==0.5.0**
Flask-Mail==0.9.1
Flask-Migrate==2.5.3
Flask-SQLAlchemy==2.4.4
flask-whooshalchemy3==0.2.0
**Flask-WTF==0.14.3**
gunicorn==20.0.4
idna==2.10
itsdangerous==1.1.0
Jinja2==2.11.2
Mako==1.1.3
MarkupSafe==1.1.1
pbr==3.1.1
psycopg2-binary==2.8.6
python-dateutil==2.8.1
python-editor==1.0.4
requests==2.24.0
six==1.15.0
SQLAlchemy==1.3.19
urllib3==1.25.10
Werkzeug==1.0.1
Whoosh==2.7.4
**WTForms==2.3.3**

Thanks,

**Comment by miguelgrinberg** [comment]
@ancalita I can't tell you what's wrong with the information you provided. You need to debug this yourself to determine what's happening. Unfortunately this is tricky to debug, you may need to add print statements in the Flask-WTF or WTForms code to determine where is the token getting lost.

**Comment by ancalita** [comment]
@miguelgrinberg Thanks for your reply! Sure, I can continue with debugging, but the next question is, where should I add the print statements (in the view function for register?) and what exactly am I looking to print?

**Comment by miguelgrinberg** [comment]
@ancalita Well, the first question is if the browser is sending a token back to the server at all. If not, then the problem is in your form, which does not have a csrf token field, or has the field but it is empty. You can verify this by looking at the source HTML of your page.

If the browser is sending a token, but you still get a failure then the token is not what the server expects. In this case you need to find the place within wtforms where the token is validated and see what token it is expected vs. the actual token that was received. Maybe the token is getting regenerated with every request for some reason, or your session (where the token is stored) is invalidated, but I'm just really coming up with ideas without knowing anything.

**Comment by ancalita** [comment]
Hi @miguelgrinberg I can confirm the browser is sending a token; additionally I set WTF_CSRF_TIME_LIMIT=None, but I'm still getting a failure.
I've placed two print statements in the register controller, for example:
_form = SignupForm()
print(form.csrf_token)
if form.validate_on_submit():
        print(form.csrf_token)_

However only the first print statement got executed and its csrf token matched the one from the browser.
Could you please give more details on this instruction, I'm uncertain how to proceed further: In this case you need to find the place within wtforms where the token is validated and see what token it is expected vs. the actual token that was received. Thank you so much!

**Comment by miguelgrinberg** [comment]
I'm not really sure how I can help. The token is probably not what wtforms expects, but I do not know why. Maybe your session is invalidated as I mentioned above, but the only reason that comes to mind is the session protection which you say you don't use, so I don't know.

**Comment by ancalita** [comment]
I think I found the problem - my application was not multithreaded, so when different users were trying to register/login on different devices, they were not able. All I had to do was add --threads <number of threads> to gunicorn command in the Procfile and the application seems to be working for different users now. Thank you for your speedy help originally!

**Comment by avnermosh** [comment]
> I think I found the problem - my application was not multithreaded, so when different users were trying to register/login on different devices, they were not able. All I had to do was add --threads to gunicorn command in the Procfile and the application seems to be working for different users now. Thank you for your speedy help originally!

@ancalita comment solved my problem as well.
In my case, I occasionally saw run time errors ```The CSRF session token is missing``` in my login function.
This happened when several users are connected from different devices/sessions.

The CSRF error happened when I was not even expecting a CSRF token (i.e. in a GET request, before the LoginForm is even rendered - see the error snippet)
I'm working in a Docker container environment, and using gunicorn for the webapp server.

error snippet:
```
  request.method GET
  BEG bad_request_error
  BEG general_exception_error
  2021-02-04 19:57:08,140 - app - ERROR - message
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/flask_wtf/csrf.py", line 249, in protect
      validate_csrf(self._get_csrf_token())
    File "/usr/local/lib/python3.9/site-packages/flask_wtf/csrf.py", line 87, in validate_csrf
      raise ValidationError('The CSRF session token is missing.')
  wtforms.validators.ValidationError: The CSRF session token is missing.
```

I changed the command from:
```gunicorn 'app:create_app()' -w 2 -b 0.0.0.0:8000```
to:
```gunicorn 'app:create_app()' --threads 4 -w 2 -b 0.0.0.0:8000```
and the problem has gone away.


**Does this mean that if more than 4 users (the number of threads) are connected, the problem can re-appear?**

**Comment by miguelgrinberg** [comment]
@avnermosh to be honest I do not understand what is the relationship between threads and CSRF tokens, so I cannot really answer your question without knowing more about your code. For example, you seem to not want to have CSRF tokens outside of forms, right? Are you using the `CsrfProtect()` class, same as the OP? That seems contradictory, since CSRF is enabled by default on forms, and `CsrfProtect()` is used to add this protection beyond the forms.

**Comment by avnermosh** [comment]
Thanks for your prompt response.
> For example, you seem to not want to have CSRF tokens outside of forms, right? 

I do in fact use CSRF tokens outside of forms.
It took me some time to understand that general CSRF protection in Flask and CSRF protection in FlaskForm are complementary:
- FlaskForm by default provides CSRF protection, so there is no need to do anything (e.g. no need to explictly add ```'{{ form.hidden_tag() }}'``` to the .html page)
- General CSRF protection covers all other requests that do not involve FlaskForm (e.g. POST,PUT,DELETE fetch requests from the javascript code)
For this I have the seting that I described in [here](https://stackoverflow.com/questions/65985400/getting-csrf-errors-from-put-fetch-request-that-does-not-involve-flask-forms), e.g.

```
app/__init__.py
  ...
  from flask_wtf.csrf import CSRFProtect, generate_csrf, validate_csrf
  ...
  csrf = CSRFProtect()
  ...
  def create_app(config_class=Config):
      app = Flask(__name__)
  ...
      csrf.init_app(app)
  ...
```

and then in every e.g. POST fetch I have e.g.
```
  const formData = new FormData();
  formData.append(...);
  
  let headersData = {
      'X-CSRF-Token': MLJ.model.csrf_token
  };
  
  let fetchData = { 
      method: 'POST', 
      headers: headersData,
      body: formData
  };
  
  let response = await fetch(queryUrl, fetchData);
```

So when I added ```CSRFProtect```, and by using ```FlaskForm```, I had other CSRF related errors (e.g. I forgot to add the headersData to a POST fetch request).
These problems were easy as they were programming faults and always repeatable (i.e. the same request kept giving the same error every time). I fixed these errors.


But the error that is mentioned here (i.e. getting the "CSRF session token is missing" error), was occuring only some times.
For example:
- if only one user was connected, I seldom got the error
- if I refreshed and tried to login again, sometimes the CSRF error would not appear, and I could log in, and from there all other requests are ok (no more CSRF errors)
- if I logged-out from another device, then occasionally, the other device, could log-in, but then the device I just logged-out from could not.

After I added the "--thread 4" to gunicorn, the problem stopped completely.
I don't know how to explain it but this is my observation.

**Comment by Sarathlal** [comment]
> I think I found the problem - my application was not multithreaded, so when different users were trying to register/login on different devices, they were not able. All I had to do was add --threads to gunicorn command in the Procfile and the application seems to be working for different users now. Thank you for your speedy help originally!

I face the same issue & solved by adding `threads` parameter in the gunicorn command.

**Comment by johannespostler** [comment]
I ran into the same problem (on a completely different application) and indeed adding the `threads` parameter to the gunicorn command changes things. However, I think it's not actually the number of threads that changes anything, but rather the fact that settings this parameter switches the worker type from [`sync` to `gthread` according to the docs](https://docs.gunicorn.org/en/stable/settings.html#threads). Not sure what happens, if one previously used another worker type (`gevent`, `tornado` etc.) - I assume this only helps if one previously used the `sync` worker class in gunicorn.

**Comment by israel-oye** [comment]
I added the `thread` param to my gunicorn command and set the `workers` to 1 as explained in [this](https://stackoverflow.com/a/64148808/16792256) _SO_ answer but I still get the ominous
```
Bad Request
The CSRF token is missing.
```
Error. I don't even know what to try next.
Yet the token shows on the HTML. Is there a way to debug this issue?
